const skillSet = [
    "Java",
    "Python",
    "JavaScript",
    "C++",
    "C#",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "Rust",
    "HTML",
    "CSS",
    "SQL",
    "NoSQL",
    "TypeScript",
    "PHP",
    "Bash",
    "Perl",
    "Lua",
    "Scala",
    "Elixir",
    "Erlang",
    "Haskell",
    "Clojure",
    "Dart",
    "Objective-C",
    "MATLAB",
    "R",
    "Groovy",
    "F#",
    "Vue.js",
    "React",
    "Angular",
    "Django",
    "Flask",
    "Spring Boot",
    "Ruby on Rails",
    "ASP.NET",
    "Laravel",
    "Express.js",
    "Node.js",
    "Meteor.js",
    "Ember.js",
    "Svelte",
    "Backbone.js",
    "Bootstrap",
    "Materialize",
    "Foundation",
    "Bulma",
    "Tailwind CSS",
    "SASS",
    "LESS",
    "Webpack",
    "Gulp",
    "Grunt",
    "NPM",
    "Yarn",
    "Docker",
    "Kubernetes",
    "Git",
    "SVN",
    "Mercurial",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "GitHub Actions",
    "Azure DevOps",
    "AWS",
    "Google Cloud Platform",
    "Microsoft Azure",
    "Firebase",
    "Heroku",
    "DigitalOcean",
    "Vagrant",
    "Ansible",
    "Terraform",
    "Puppet",
    "Chef",
    "Selenium",
    "Cypress",
    "JUnit",
    "TestNG",
    "Mocha",
    "Jest",
    "Enzyme",
    "Karma",
    "Protractor",
    "REST",
    "GraphQL",
    "SOAP",
    "WebSockets",
    "MVC",
    "MVVM",
    "OOP",
    "Functional Programming",
    "Reactive Programming",
    "Agile Methodology",
    "Scrum",
    "Kanban",
    "TDD",
    "BDD",
    "CI/CD",
    "DevOps",
    "Microservices",
    "Blockchain",
    "Elm",
    "Julia",
    "OCaml",
    "Scheme",
    "Forth",
    "Prolog",
    "Lisp",
    "Smalltalk",
    "Cobol",
    "Fortran",
    "ABAP",
    "Delphi",
    "Pascal",
    "Ada",
    "Crystal",
    "Nim",
    "Reason",
    "Zig",
    "Assembly",
    "GraphQL API",
    "Apollo",
    "Redux",
    "MobX",
    "Vuex",
    "Next.js",
    "Nuxt.js",
    "Gatsby",
    "Jekyll",
    "Hugo",
    "Electron",
    "Cordova",
    "Flutter",
    "React Native",
    "Xamarin",
    "Ionic",
    "NativeScript",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-Learn",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "D3.js",
    "Three.js",
    "Unity",
    "Unreal Engine",
    "Blender",
    "OpenGL",
    "WebGL",
    "Vulkan",
    "CUDA",
    "OpenCV",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "MariaDB",
    "Redis",
    "Cassandra",
    "Elasticsearch",
    "Neo4j",
    "Couchbase",
    "DynamoDB",
    "Oracle Database",
    "SQL Server",
    "DB2",
    "Hadoop",
    "Spark",
    "Kafka",
    "RabbitMQ",
    "ZeroMQ",
    "ActiveMQ",
    "NATS",
    "GraphQL",
    "Falcor",
    "WebAssembly",
    "Solidity",
    "Rust Wasm",
    "Docker Compose",
    "Knative",
    "Prometheus",
    "Grafana",
    "Logstash",
    "Kibana",
    "Elastic APM",
    "New Relic",
    "DataDog",
    "Splunk",
    "Nagios",
    "Zabbix",
    "Graylog",
    "OpenTracing",
    "Jaeger",
    "Zipkin",
    "Consul",
    "Etcd",
    "Zookeeper",
    "Serverless Framework",
    "SAM",
    "CloudFormation",
    "Bicep",
    "Pulumi",
    "RxJS",
    "Akka",
    "Vert.x",
    "Quarkus",
    "Micronaut",
    "Helidon",
    "FastAPI",
    "Sanic",
    "Tornado",
    "Falcon",
    "Hapi",
    "Koa",
    "Sinatra",
    "Flask-RESTful",
    "Django REST framework",
    "WebRTC",
    "Socket.IO",
    "Quasar Framework",
    "Strapi",
    "Ghost",
    "RedwoodJS",
    "Blitz.js",
    "Sapper",
    "Stencil",
    "LitElement",
    "Alpine.js",
    "Hyperapp",
    "PixiJS",
    "BabylonJS",
    "A-Frame",
    "AR.js",
    "VR Development",
    "Machine Learning Ops",
    "Natural Language Processing",
    "Computer Vision",
    "Deep Learning",
    "Reinforcement Learning",
    "Genetic Algorithms",
    "Data Visualization",
    "Data Engineering",
    "Big Data Analysis",
    "IoT Development",
    "Blockchain Development",
    "Smart Contract Development",
    "DApp Development",
    "Quantum Computing",
    "Cybersecurity",
    "Penetration Testing",
    "Ethical Hacking",
    "Forensics",
    "Cryptography",
    "ARCore",
    "ARKit",
    "Vuforia",
    "Unity ML-Agents",
    "Shader Development",
    "Game Physics",
    "AI in Games",
    "Mobile Game Development",
    "Responsive Web Design",
    "Progressive Web Apps",
    "AMP (Accelerated Mobile Pages)",
    "SEO Optimization",
    "Performance Optimization",
    "Accessibility",
    "Internationalization",
    "Web Audio API",
    "Canvas API",
    "Service Workers",
    "IndexedDB",
    "WebGL 2.0",
    "WebXR",
    "Hololens Development",
    "Magic Leap Development",
    "VRChat Development",
    "Godot Engine",
    "Solar2D",
    "Phaser",
    "MelonJS",
    "Construct 3",
    "GameMaker Studio 2",
    "Apache Cordova",
    "Capacitor",
    "Quokka.js",
    "Wallaby.js",
    "ESLint",
    "Prettier",
    "Stylelint",
    "SonarQube",
    "Code Climate",
    "Continuous Integration",
    "Continuous Deployment",
    "Infrastructure as Code",
    "Monitoring and Alerting",
    "Cloud Security",
    "Containerization",
    "Microfrontend Architecture",
    "Domain-Driven Design",
    "Event-Driven Architecture",
    "Server-Side Rendering",
    "Static Site Generation",
    "Headless CMS",
    "Jamstack",
    "GraphQL Subscriptions",
    "Apollo Federation",
    "Prisma",
    "ORM (Object-Relational Mapping)",
    "ODM (Object-Document Mapping)",
    "API Design",
    "API Management",
    "API Testing",
    "Microservices Testing",
    "Load Testing",
    "Performance Testing",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Behavior-Driven Development",
    "Pair Programming",
    "Mob Programming",
    "Code Review",
    "Refactoring",
    "Design Patterns",
    "System Design",
    "Architecture Patterns",
    "High Availability Systems",
    "Scalable Systems",
    "Distributed Systems",
    "Project Management",
    "Team Leadership",
    "Data Science",
    "Public Speaking",
    "Budeget Management",
    "Leardership",
    "Communication",
    "Interpersonal Skills",
    "Ansys (Software)",
    "AutoCAD",
    "Catia",
    "UI/UX Design",
    "Material-UI",
    "Cloud Computing",
    "SDLC",
    "Analytical Skills",
    "Machine Learning",
    "Test Automation",
    "Network Security",
    "Intrusion Detection",
    "Vulnerability Assessment",
    "SIEM",
    "Test Planning",
    "Manual Testing",
    "Security Testing",
    "Agile Testing",
    "Agile Methodologies",
    "Risk Assessment",
    "Stakeholder Management",
    "Stakeholder Engagement",
    "Change Management",
    "Scrum Master Certification",
    "System Design",
    "Microservices Architecture",
    "Serverless Computing",
    "AR/VR Development",
    "CI/CD Pipelines",
    "RESTful APIs",
];

export default skillSet;
